#! /bin/bash
magenta=$(tput setaf 5)
bold=$(tput bold)
reset=$(tput sgr0)

echo "${bold} ${magenta}starting to clean apt of unnecessary files ${reset}"
apt clean -y
apt autoremove -y; 
echo "${bold} ${magenta} all done cleaning up apt, now updating and upgrading ${reset}"
apt update
apt full-upgrade -y
apt dist-upgrade -y
echo "${bold} ${magenta} All finished upgrading the system, enjoy. ${reset}"
